apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: trirahmaagustin/product:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: spring.application.name
          value: "product"
        - name: eureka.client.service-url.defaultZone
          value: "http://eurekaserver:8761/eureka/"
        - name: spring.datasource.url
          value: "jdbc:mysql://mysql:3306/dbecommerce_produk?useSSL=false&serverTimezone=UTC"
        - name: spring.datasource.username
          value: "root"
        - name: spring.datasource.password
          value: "root_password"
